spring.datasource.url=jdbc:mysql://localhost:3306/insurance_db?createDatabaseIfNotExist=true
spring.datasource.username=insurance_db
spring.datasource.password=Fredo@05
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
